[project]
name = "backend"
version = "0.1.0"
description = "lily agent that find's and organize articles/blogs to read on specific topic"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.2.4",
    "httpx>=0.28.1",
    "langgraph>=1.2.11",
    "pathlib>=1.0.1",
    "pydantic>=2.12.5,<2.13.0",
    "python-dotenv>=1.2.3",
    "sqlmodel>=0.0.42",
]

[tool.fastapi]
entrypoint = "app.main:app"

